version: "3.4"

services:
  webserver:
    image: nginx:alpine
    container_name: app-webserver
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./var/log:/app/var/log
      - phpsocket:/var/run/php
    ports:
      - "80:80"

  php-fpm:
    build: docker/php-fpm
    container_name: app-php-fpm
    working_dir: /app
    volumes:
      - .:/app
      - phpsocket:/var/run/php
      #- ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  postgres:
    image: postgres:12-alpine
    container_name: app-postgres
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
volumes:
  phpsocket: